package middleware

import (
	"net/http"
	"os"

	// _ "github.com/MykolaSainiuk/schatgo/docs" // docs is generated by Swag CLI, you have to import it.
	// swaggerFiles "github.com/swaggo/files"
	httpSwagger "github.com/swaggo/http-swagger/v2"
)

func Swagger() http.HandlerFunc {
	host := os.Getenv("HOST")
	port := os.Getenv("PORT")

	return httpSwagger.Handler(
		httpSwagger.URL("http://" + host + ":" + port + "/swagger/doc.json"), //The url pointing to API definition
	)
}
